config/routes.rb
Rails.application.routes.draw do
  get 'calculations/show'
  get 'calculations/new'
  resources :calculations
  root 'calculations#new'
end

app/models/calculation.rb
class Calculation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calculations_controller.rb
require 'calculation_runner'

class CalculationsController < ApplicationController
  def show
    @calc = Calculation.find(params[:id])
  end

  def new
  end

  def create
    runner_klass = CalculationRunner.new(inputs: params[:inputs])
    @calc = Calculation.new
    @calc.inputs = runner_klass.displayed_inputs
    @calc.output = runner_klass.run_calculation
    # normally I would include some validation here before saving anything to DB
    @calc.save
    redirect_to @calc
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculations_helper.rb
module CalculationsHelper
end

app/views/calculations/new.html.erb
<h1>Simple Calculator:</h1>
<%= form_tag(calculations_path, method: "post") do %>
  <p>
    <%= label_tag(:inputs, "Enter the calculation you'd like to run here:") %>
  </p>
  <p>
    Note: you can supply multiple numbers, but only one operator (+, -, /, or *)
  </p>
  <%= text_field_tag(:inputs, "", placeholder: "2 + 2") %>
  <%= submit_tag("Calculate!") %>
<% end %>

app/views/calculations/show.html.erb
<h1>Calculated Value:</h1>
<p>
  The following was calculated:
</p>
<p>
  <%= @calc.inputs %>
</p>
<p>
  and here is the result:
</p>
<p>
  <%= @calc.output %>
</p>

<%= link_to "Start a new calculation", calculations_new_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calculator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>